"""Add image support to room messages

Revision ID: 373985167d27
Revises: 9dc65a544c4f
Create Date: 2026-05-02 20:50:08.387477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '373985167d27'
down_revision: Union[str, None] = '9dc65a544c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indexed_user_id', sa.UUID(), nullable=True),
    sa.Column('indexed_post_id', sa.UUID(), nullable=True),
    sa.Column('indexed_room_id', sa.UUID(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('search_category', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indexed_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indexed_room_id'], ['community_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indexed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_index_indexed_user_id'), 'search_index', ['indexed_user_id'], unique=False)
    op.create_index(op.f('ix_search_index_search_category'), 'search_index', ['search_category'], unique=False)
    op.drop_index('ix_global_messages_archive_created_at', table_name='global_messages_archive')
    op.drop_index('ix_global_messages_archive_sender_id', table_name='global_messages_archive')
    op.drop_table('global_messages_archive')
    op.drop_index('ix_point_transactions_created_at', table_name='point_transactions')
    op.drop_index('ix_point_transactions_from_user', table_name='point_transactions')
    op.drop_index('ix_point_transactions_to_user', table_name='point_transactions')
    op.drop_table('point_transactions')
    op.drop_index('ix_profile_trending_scores_composite_score', table_name='profile_trending_scores')
    op.drop_index('ix_profile_trending_scores_trending_rank', table_name='profile_trending_scores')
    op.drop_table('profile_trending_scores')
    op.drop_index('ix_wallet_points_user_id', table_name='wallet_points')
    op.drop_table('wallet_points')
    op.drop_index('ix_ai_conversations_user_id', table_name='ai_conversations')
    op.create_index(op.f('ix_ai_conversations_created_at'), 'ai_conversations', ['created_at'], unique=False)
    op.drop_index('ix_ai_messages_conversation_id', table_name='ai_messages')
    op.create_index(op.f('ix_alter_egos_created_at'), 'alter_egos', ['created_at'], unique=False)
    op.drop_index('ix_beauty_scores_user_id', table_name='beauty_scores')
    op.drop_index('ix_chat_threads_last_msg', table_name='chat_threads')
    op.drop_index('ix_chat_threads_user_a', table_name='chat_threads')
    op.drop_index('ix_chat_threads_user_a_created', table_name='chat_threads')
    op.drop_index('ix_chat_threads_user_b', table_name='chat_threads')
    op.drop_index('ix_chat_threads_user_b_created', table_name='chat_threads')
    op.create_index(op.f('ix_chat_threads_created_at'), 'chat_threads', ['created_at'], unique=False)
    op.drop_index('ix_clout_balances_market_cap_desc', table_name='clout_balances')
    op.create_index(op.f('ix_clout_balances_created_at'), 'clout_balances', ['created_at'], unique=False)
    op.drop_constraint('uq_club_member', 'club_members', type_='unique')
    op.drop_index('ix_club_messages_club_id', table_name='club_messages')
    op.drop_index('ix_community_rooms_is_active_created_at', table_name='community_rooms')
    op.drop_index('ix_community_rooms_name_trgm', table_name='community_rooms', postgresql_using='gin')
    op.create_index(op.f('ix_community_rooms_created_at'), 'community_rooms', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_rooms_is_active'), 'community_rooms', ['is_active'], unique=False)
    op.drop_index('ix_email_verifications_token', table_name='email_verifications')
    op.create_index(op.f('ix_email_verifications_created_at'), 'email_verifications', ['created_at'], unique=False)
    op.drop_index('ix_engagement_user_created', table_name='engagement_events')
    op.create_index(op.f('ix_engagement_events_created_at'), 'engagement_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.add_column('global_messages', sa.Column('image_url', sa.String(length=1024), nullable=True))
    op.add_column('global_messages', sa.Column('image_type', sa.String(length=16), nullable=True))
    op.drop_index('ix_global_messages_sender_id', table_name='global_messages')
    op.drop_index('ix_login_dividends_claimed_at', table_name='login_dividends')
    op.drop_index('ix_login_dividends_user_id', table_name='login_dividends')
    op.create_index(op.f('ix_login_dividends_created_at'), 'login_dividends', ['created_at'], unique=False)
    op.drop_index('ix_orders_storefront_id', table_name='orders')
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_post_comments_created_at'), 'post_comments', ['created_at'], unique=False)
    op.drop_index('ix_post_likes_post_id', table_name='post_likes')
    op.create_index(op.f('ix_post_likes_created_at'), 'post_likes', ['created_at'], unique=False)
    op.drop_index('ix_posts_content_trgm', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_posts_rank_score', table_name='posts')
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.alter_column('profile_impressions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_profile_impressions_target_user_created_at', table_name='profile_impressions')
    op.create_index(op.f('ix_profile_impressions_created_at'), 'profile_impressions', ['created_at'], unique=False)
    op.create_index(op.f('ix_profile_impressions_target_user_id'), 'profile_impressions', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_profile_impressions_visitor_id'), 'profile_impressions', ['visitor_id'], unique=False)
    op.alter_column('room_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('room_messages', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('room_messages', sa.Column('image_type', sa.String(length=50), nullable=True))
    op.drop_index('ix_room_messages_room_id_created_at', table_name='room_messages')
    op.create_index(op.f('ix_room_messages_created_at'), 'room_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_room_messages_room_id'), 'room_messages', ['room_id'], unique=False)
    op.drop_index('ix_storefronts_sales_vol', table_name='storefronts')
    op.drop_index('ix_storefronts_owner_id', table_name='storefronts')
    op.create_index(op.f('ix_storefronts_owner_id'), 'storefronts', ['owner_id'], unique=True)
    op.create_index(op.f('ix_storefronts_created_at'), 'storefronts', ['created_at'], unique=False)
    op.drop_index('ix_token_tx_created_at', table_name='token_transactions')
    op.drop_index('ix_token_tx_from', table_name='token_transactions')
    op.drop_index('ix_token_tx_to', table_name='token_transactions')
    op.create_index(op.f('ix_token_transactions_created_at'), 'token_transactions', ['created_at'], unique=False)
    op.alter_column('user_notifications', 'notification_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_notifications_recipient_created_at', table_name='user_notifications')
    op.drop_index('ix_user_notifications_recipient_id_is_read', table_name='user_notifications')
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_recipient_id'), 'user_notifications', ['recipient_id'], unique=False)
    op.alter_column('user_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_ratings_created_at', table_name='user_ratings')
    op.create_index(op.f('ix_user_ratings_created_at'), 'user_ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_ratings_rater_id'), 'user_ratings', ['rater_id'], unique=False)
    op.drop_index('ix_users_attractiveness_percentage_desc', table_name='users')
    op.drop_index('ix_users_beauty_score_cached_desc', table_name='users')
    op.drop_index('ix_users_display_name_trgm', table_name='users', postgresql_using='gin', postgresql_where='(display_name IS NOT NULL)')
    op.drop_index('ix_users_hot_rank_position', table_name='users')
    op.drop_index('ix_users_hot_score_cached_desc', table_name='users')
    op.drop_index('ix_users_rating_score_desc', table_name='users')
    op.drop_index('ix_users_trending_score_cached_desc', table_name='users')
    op.drop_index('ix_users_username_trgm', table_name='users', postgresql_using='gin')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_column('users', 'beauty_score_cached')
    op.drop_column('users', 'engagement_7d_cached')
    op.drop_column('users', 'cover_image_url')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'trending_score_cached')
    op.drop_column('users', 'trending_rank')
    op.drop_column('users', 'rating_updated_at')
    op.drop_column('users', 'boost_expires_at')
    op.drop_column('users', 'has_boost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_boost', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('boost_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rating_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('trending_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('trending_score_cached', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('cover_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('engagement_7d_cached', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('beauty_score_cached', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_username_trgm', 'users', ['username'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_trending_score_cached_desc', 'users', [sa.text('trending_score_cached DESC')], unique=False)
    op.create_index('ix_users_rating_score_desc', 'users', [sa.text('rating_score DESC')], unique=False)
    op.create_index('ix_users_hot_score_cached_desc', 'users', ['hot_score_cached'], unique=False)
    op.create_index('ix_users_hot_rank_position', 'users', ['hot_rank_position'], unique=False)
    op.create_index('ix_users_display_name_trgm', 'users', ['display_name'], unique=False, postgresql_using='gin', postgresql_where='(display_name IS NOT NULL)')
    op.create_index('ix_users_beauty_score_cached_desc', 'users', [sa.text('beauty_score_cached DESC')], unique=False)
    op.create_index('ix_users_attractiveness_percentage_desc', 'users', [sa.text('attractiveness_percentage DESC')], unique=False)
    op.drop_index(op.f('ix_user_ratings_rater_id'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_created_at'), table_name='user_ratings')
    op.create_index('ix_user_ratings_created_at', 'user_ratings', [sa.text('created_at DESC')], unique=False)
    op.alter_column('user_ratings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_notifications_recipient_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.create_index('ix_user_notifications_recipient_id_is_read', 'user_notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index('ix_user_notifications_recipient_created_at', 'user_notifications', ['recipient_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('user_notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_notifications', 'notification_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_token_transactions_created_at'), table_name='token_transactions')
    op.create_index('ix_token_tx_to', 'token_transactions', ['to_user_id'], unique=False)
    op.create_index('ix_token_tx_from', 'token_transactions', ['from_user_id'], unique=False)
    op.create_index('ix_token_tx_created_at', 'token_transactions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_storefronts_created_at'), table_name='storefronts')
    op.drop_index(op.f('ix_storefronts_owner_id'), table_name='storefronts')
    op.create_index('ix_storefronts_owner_id', 'storefronts', ['owner_id'], unique=False)
    op.create_index('ix_storefronts_sales_vol', 'storefronts', ['total_sales_volume'], unique=False)
    op.drop_index(op.f('ix_room_messages_room_id'), table_name='room_messages')
    op.drop_index(op.f('ix_room_messages_created_at'), table_name='room_messages')
    op.create_index('ix_room_messages_room_id_created_at', 'room_messages', ['room_id', sa.text('created_at DESC')], unique=False)
    op.drop_column('room_messages', 'image_type')
    op.drop_column('room_messages', 'image_url')
    op.alter_column('room_members', 'joined_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_profile_impressions_visitor_id'), table_name='profile_impressions')
    op.drop_index(op.f('ix_profile_impressions_target_user_id'), table_name='profile_impressions')
    op.drop_index(op.f('ix_profile_impressions_created_at'), table_name='profile_impressions')
    op.create_index('ix_profile_impressions_target_user_created_at', 'profile_impressions', ['target_user_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('profile_impressions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.create_index('ix_posts_rank_score', 'posts', ['rank_score'], unique=False)
    op.create_index('ix_posts_content_trgm', 'posts', ['content'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_post_likes_created_at'), table_name='post_likes')
    op.create_index('ix_post_likes_post_id', 'post_likes', ['post_id'], unique=False)
    op.drop_index(op.f('ix_post_comments_created_at'), table_name='post_comments')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.create_index('ix_orders_storefront_id', 'orders', ['storefront_id'], unique=False)
    op.drop_index(op.f('ix_login_dividends_created_at'), table_name='login_dividends')
    op.create_index('ix_login_dividends_user_id', 'login_dividends', ['user_id'], unique=False)
    op.create_index('ix_login_dividends_claimed_at', 'login_dividends', ['claimed_at'], unique=False)
    op.create_index('ix_global_messages_sender_id', 'global_messages', ['sender_id'], unique=False)
    op.drop_column('global_messages', 'image_type')
    op.drop_column('global_messages', 'image_url')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    op.drop_index(op.f('ix_engagement_events_created_at'), table_name='engagement_events')
    op.create_index('ix_engagement_user_created', 'engagement_events', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_email_verifications_created_at'), table_name='email_verifications')
    op.create_index('ix_email_verifications_token', 'email_verifications', ['token'], unique=False)
    op.drop_index(op.f('ix_community_rooms_is_active'), table_name='community_rooms')
    op.drop_index(op.f('ix_community_rooms_created_at'), table_name='community_rooms')
    op.create_index('ix_community_rooms_name_trgm', 'community_rooms', ['name'], unique=False, postgresql_using='gin')
    op.create_index('ix_community_rooms_is_active_created_at', 'community_rooms', ['is_active', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_club_messages_club_id', 'club_messages', ['club_id'], unique=False)
    op.create_unique_constraint('uq_club_member', 'club_members', ['club_id', 'user_id'])
    op.drop_index(op.f('ix_clout_balances_created_at'), table_name='clout_balances')
    op.create_index('ix_clout_balances_market_cap_desc', 'clout_balances', [sa.text('market_cap DESC')], unique=False)
    op.drop_index(op.f('ix_chat_threads_created_at'), table_name='chat_threads')
    op.create_index('ix_chat_threads_user_b_created', 'chat_threads', ['user_b_id', sa.text('last_message_at DESC')], unique=False)
    op.create_index('ix_chat_threads_user_b', 'chat_threads', ['user_b_id'], unique=False)
    op.create_index('ix_chat_threads_user_a_created', 'chat_threads', ['user_a_id', sa.text('last_message_at DESC')], unique=False)
    op.create_index('ix_chat_threads_user_a', 'chat_threads', ['user_a_id'], unique=False)
    op.create_index('ix_chat_threads_last_msg', 'chat_threads', ['last_message_at'], unique=False)
    op.create_index('ix_beauty_scores_user_id', 'beauty_scores', ['user_id'], unique=False)
    op.drop_index(op.f('ix_alter_egos_created_at'), table_name='alter_egos')
    op.create_index('ix_ai_messages_conversation_id', 'ai_messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_ai_conversations_created_at'), table_name='ai_conversations')
    op.create_index('ix_ai_conversations_user_id', 'ai_conversations', ['user_id'], unique=False)
    op.create_table('wallet_points',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_spent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wallet_points_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wallet_points_pkey'),
    sa.UniqueConstraint('user_id', name='uq_wallet_points_user')
    )
    op.create_index('ix_wallet_points_user_id', 'wallet_points', ['user_id'], unique=False)
    op.create_table('profile_trending_scores',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('market_cap_component', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('hot_ratio_component', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('content_power_component', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('engagement_velocity_component', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('composite_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('trending_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='profile_trending_scores_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='profile_trending_scores_pkey')
    )
    op.create_index('ix_profile_trending_scores_trending_rank', 'profile_trending_scores', ['trending_rank'], unique=False)
    op.create_index('ix_profile_trending_scores_composite_score', 'profile_trending_scores', ['composite_score'], unique=False)
    op.create_table('point_transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'completed'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name='point_transactions_from_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name='point_transactions_to_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='point_transactions_pkey')
    )
    op.create_index('ix_point_transactions_to_user', 'point_transactions', ['to_user_id'], unique=False)
    op.create_index('ix_point_transactions_from_user', 'point_transactions', ['from_user_id'], unique=False)
    op.create_index('ix_point_transactions_created_at', 'point_transactions', ['created_at'], unique=False)
    op.create_table('global_messages_archive',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_reward', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_rush_hour', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='global_messages_archive_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='global_messages_archive_pkey')
    )
    op.create_index('ix_global_messages_archive_sender_id', 'global_messages_archive', ['sender_id'], unique=False)
    op.create_index('ix_global_messages_archive_created_at', 'global_messages_archive', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_search_index_search_category'), table_name='search_index')
    op.drop_index(op.f('ix_search_index_indexed_user_id'), table_name='search_index')
    op.drop_table('search_index')
    # ### end Alembic commands ###
