"""Make global message sender nullable

Revision ID: 9dc65a544c4f
Revises: aa29a70698b5
Create Date: 2026-05-02 04:26:02.360707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9dc65a544c4f'
down_revision: Union[str, None] = '024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_messages', 'sender_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
