"""Add database indexes for billion-scale optimization

Revision ID: e45746a4796c
Revises: 373985167d27
Create Date: 2026-05-02 21:12:36.504298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e45746a4796c'
down_revision: Union[str, None] = '373985167d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_a_id'), 'chat_threads', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_user_b_id'), 'chat_threads', ['user_b_id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_rank_score'), 'posts', ['rank_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_rank_score'), table_name='posts')
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_chat_threads_user_b_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_user_a_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    # ### end Alembic commands ###
