"""Add intercollege profile fields: college_name, major, interests

Revision ID: k00200f9241h
Revises: j99199e8130g
Create Date: 2026-05-15 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'k00200f9241h'
down_revision = 'j99199e8130g'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('college_name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('interests', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_column('users', 'major')
    op.drop_column('users', 'college_name')
    # ### end Alembic commands ###
